// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  lessonsSidebar: [
    {
      type: 'doc',
      id: 'intro',
      label: 'Welcome',
    },
    {
      type: 'category',
      label: 'Setup',
      items: [{ type: 'autogenerated', dirName: 'setup' }],
    },
    {
      type: 'category',
      label: 'Database / SQL',
      items: [{ type: 'autogenerated', dirName: 'database' }],
    },
    {
      type: 'category',
      label: 'Python',
      items: [{ type: 'autogenerated', dirName: 'python' }],
    },
    {
      type: 'category',
      label: 'React',
      items: [{ type: 'autogenerated', dirName: 'react' }],
    },
    {
      type: 'category',
      label: 'Node.js',
      items: [{ type: 'autogenerated', dirName: 'nodejs' }],
    },
    {
      type: 'category',
      label: 'PHP',
      items: [{ type: 'autogenerated', dirName: 'php' }],
    },
    {
      type: 'category',
      label: 'Java',
      items: [{ type: 'autogenerated', dirName: 'java' }],
    },
  ],
};

export default sidebars;
